version: "3.5"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /server
    env_file:
      - .env
    volumes:
      - .:/server 
    ports:
      - "80:80"
    depends_on:
      - db
    entrypoint: go run main.go
    restart: always
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always